version: "3.7"

services: 
  front:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./client:/app
      - /app/node_modules

  app:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    volumes: 
      - ./backend:/app
      - '/app/node_modules'
    depends_on: 
      - mysql_server
  
  mysql_server:
    image: mysql:5.7
    environment: 
      - MYSQL_DATABASE=minidex
      - MYSQL_USER=brayan
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 23306:3306
